// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.wishop.admin.configurations;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;

public class DatabaseConfig_devDatabaseConnection_92e38a1595_Test {

    @InjectMocks
    DatabaseConfig databaseConfig;

    @Mock
    DriverManagerDataSource dataSource;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        when(dataSource.getDriverClassName()).thenReturn("com.mysql.jdbc.Driver");
        when(dataSource.getUrl()).thenReturn("jdbc:mysql://localhost:3306/wishop");
        when(dataSource.getUsername()).thenReturn("testUser");
        when(dataSource.getPassword()).thenReturn("testPassword");
    }

    @Test
    public void testDevDatabaseConnection() {
        DataSource result = databaseConfig.devDatabaseConnection();
        assertNotNull(result);
        assertEquals("com.mysql.jdbc.Driver", result.getDriverClassName());
        assertEquals("jdbc:mysql://localhost:3306/wishop", result.getUrl());
        assertEquals("testUser", result.getUsername());
        assertEquals("testPassword", result.getPassword());
    }

    @Test
    public void testDevDatabaseConnection_Failure() {
        when(dataSource.getDriverClassName()).thenReturn(null);
        DataSource result = databaseConfig.devDatabaseConnection();
        assertNull(result.getDriverClassName());
    }
}
