// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.wishop.admin.configurations;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
public class DatabaseConfig_testDatabaseConnection_315883f8e9_Test {

    @InjectMocks
    DatabaseConfig databaseConfig;

    @Mock
    DataSource dataSource;

    @Value("${spring.datasource.url}")
    private String url;

    @Value("${spring.datasource.driverClassName}")
    private String driverClassName;

    @Test
    public void testTestDatabaseConnection_Success() {
        when(databaseConfig.testDatabaseConnection()).thenReturn("DB Connection to RDS_TEST - Low Cost Instance");
        String result = databaseConfig.testDatabaseConnection();
        assertEquals("DB Connection to RDS_TEST - Low Cost Instance", result);
    }

    @Test
    public void testTestDatabaseConnection_Failure() {
        when(databaseConfig.testDatabaseConnection()).thenReturn("DB Connection failed");
        String result = databaseConfig.testDatabaseConnection();
        assertEquals("DB Connection failed", result);
    }
}
