// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.wishop.admin.security;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

public class SecurityCredentialsConfig_passwordEncoder_6adf7f806b_Test {

    @Test
    public void testPasswordEncoderNotNull() {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        Assertions.assertNotNull(encoder);
    }

    @Test
    public void testPasswordEncoding() {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        String rawPassword = "password";
        String encodedPassword = encoder.encode(rawPassword);
        Assertions.assertTrue(encoder.matches(rawPassword, encodedPassword));
    }
}
