// Test generated by RoostGPT for test testJavaParserAst using AI Type Open AI and AI Model gpt-4

package com.wishop.admin.security;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;
import org.springframework.beans.factory.annotation.Autowired;
import com.wishop.common.configurations.JwtConfig;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class SecurityCredentialsConfig_jwtConfig_74eb3efb60_Test {

    @Autowired
    private SecurityCredentialsConfig securityCredentialsConfig;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testJwtConfigNotNull() {
        JwtConfig jwtConfig = securityCredentialsConfig.jwtConfig();
        assertNotNull(jwtConfig, "JwtConfig should not be null");
    }

    @Test
    public void testJwtConfigInstance() {
        JwtConfig jwtConfig = securityCredentialsConfig.jwtConfig();
        assertTrue(jwtConfig instanceof JwtConfig, "jwtConfig should be instance of JwtConfig");
    }
}
